### ISSUE TITLE
누락된 오류코드 추가

### ISSUE THREAD

**Issue by euijoong-nhntoast** [TOAST-DOCS/Face-Recognition#58]
이미지를 bytes 로 전달하는 경우, base64 encoding 오류에 대한 오류코드가 누락되어서 추가가 필요하다.
-45030

**Comment by jinsam-kim** [comment]
알파에 커밋 완료

**Comment by euijoong-nhntoast** [comment]
번역등 작업 완료.
10/4 배포 예정
